# This file was generated by GoReleaser. DO NOT EDIT.
class Smock < Formula
  desc ""
  homepage ""
  version "0.1.7"

  if OS.mac?
    url "https://github.com/broothie/smock/releases/download/v0.1.7/smock_0.1.7_darwin_amd64.tar.gz"
    sha256 "55cdd88a3585b7008b35b6b4df2376bf77242c15df756f4c80c0366fda78031c"
  elsif OS.linux?
    url "https://github.com/broothie/smock/releases/download/v0.1.7/smock_0.1.7_linux_amd64.tar.gz"
    sha256 "735adf055b707fc73eeb7b61b51e7cb9d9206161decd4510e14523a8cba3d6e4"
  end

  def install
    bin.install "smock"
  end
end
