# This file was generated by GoReleaser. DO NOT EDIT.
class Smock < Formula
  desc "smock - a server mock"
  homepage "https://github.com/broothie/smock"
  version "0.1.9"

  if OS.mac?
    url "https://github.com/broothie/smock/releases/download/v0.1.9/smock_0.1.9_darwin_amd64.tar.gz"
    sha256 "110fdfdd5cc384870c7a63b485c0eb8bc87cdaa69fb61574ad86881bc3e86d01"
  elsif OS.linux?
    url "https://github.com/broothie/smock/releases/download/v0.1.9/smock_0.1.9_linux_amd64.tar.gz"
    sha256 "e490b561911447e488b9cd7170d95660eae75603cba0b3ad607c62604a1b37e9"
  end

  def install
    bin.install "smock"
  end
end
